### ISSUE TITLE
class Nameについて

### ISSUE THREAD

**Issue by matsumoto777** [kmizuno1/Task1#2]
```
class Name:NSObject{
    var id:Int
    var name:String

    init(data: (Int,String)){
        id = data.0
        name = data.1
    }
}
```

1) NSObjectを継承しているのはなぜでしたっけ？

2) mutableになっていますがこれは意図的ですか？
つまり、メンバ変数がvarになっており後で外から書き換え可能になっていますが、書き換えられる必要があるでしょうか？
また、このクラスを利用する箇所は、書き換えられることを前提として整合性を取らねばならないと思いますが、そのようになっているでしょうか？
ということです。

3) コンストラクタにTupleで渡していますが、これは意図的ですか？
普通に考えたら、```init( id:Int, name:String )```となると思いますが。

**Comment by kmizuno1** [comment]
1. 意図していないため、継承をやめました。
2. 意図していないため、継承をやめました。

**Comment by matsumoto777** [comment]
平間さんの完成形を見てください

**Comment by kmizuno1** [comment]
Nameクラスのメンバ変数を小文字に変更しました。
