### ISSUE TITLE
追加案件：腕力パラメーターの追加

### ISSUE THREAD

**Issue by matsumoto777** [kmizuno1/Task1#6]
1) 表示する内容に「腕力」を追加してください
2) 腕力のデータは下記の通りです
3) 腕力の強い順でソートするボタンを設置してください

#### 腕力データ
| 名前 | 腕力 |
| -- | -- |
| Shiro | 5 |
| Lina | 20 |
| Wakaba | 1 |
| Rin | 1000 |

**Comment by kmizuno1** [comment]
腕力パラメータを追加しました。

**Comment by matsumoto777** [comment]
OKです
